
name : Build on PR

on: 
  pull_request: 
    branches: 
      - master


jobs: 
  build: 
    
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install npm@latest -g

      - name: Install Turbo
        run: cd.. && npm install turbo --global

      - name: Run Build
        run: cd.. && npm run build