name: Build on PR
 
on:
  pull_request:
    branches: ["master"]
 
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Verify Next.js Installation
        run: npx next --version || echo "Next.js is missing!"

      - name: Build Docs Manually (Debugging)
        run: cd apps/docs && npx next build

      - name: Build Webs Manually (Debugging)
        run: cd apps/web && npx next build

      - name: Build with Turbo (Debug Mode)
        run: npx turbo run build --debug
