name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
# Things are not happening on pull request 
# only if someone push to master branch 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env: 
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Printing REDIS_URL
        run:  echo "My REDIS_URL is ${{ env.REDIS_URL}}"

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/Dockerfile.user
          push: true
          environment: Production
          tags: ${{ secrets.DOCKER_USERNAME }}/zenpay:latest
          build-args: |
            REDIS_URL=${{ env.REDIS_URL }}

      # - name: Verify Pushed Image
      #   run: docker run jaibhagtani/zenpay:latest

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          scripts: |
            docker pull jaibhagtani/zenpay:latest
            docker stop zenpay || true
            docker rm zenpay || true
            docker run -d --name zenpay-user -p 3005:3000 -e REDIS_URL=${{ env.REDIS_URL }} jaibhagtani/zenpay:latest


    